apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: l3lb
  namespace: default
  labels:
    k8s-app: l3lb
spec:
  selector:
    matchLabels:
      name: l3lb
  template:
    metadata:
      labels:
        name: l3lb
    spec:
      hostNetwork: true
      automountServiceAccountToken: true
      containers:
      - name: l3lb
        image: images.local:30500/l3lb
        env:
        - name: "L3LB_PREFIX"
          value: "10.0.100.0/24"
        - name: "L3LB_INTERFACE"
          value: "lo"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
